build(lint-staged): update dependency lint-staged from 15.4.1 to 15.5.2 (#68)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [lint-staged](https://redirect.github.com/lint-staged/lint-staged) |
[`^15.4.1` ->
`^15.5.2`](https://renovatebot.com/diffs/npm/lint-staged/15.4.1/15.5.2)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/lint-staged/15.5.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/lint-staged/15.5.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/lint-staged/15.4.1/15.5.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/lint-staged/15.4.1/15.5.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>lint-staged/lint-staged (lint-staged)</summary>

###
[`v15.5.2`](https://redirect.github.com/lint-staged/lint-staged/blob/HEAD/CHANGELOG.md#1552)

[Compare
Source](https://redirect.github.com/lint-staged/lint-staged/compare/v15.5.1...v15.5.2)

##### Patch Changes

-
[#&#8203;1544](https://redirect.github.com/lint-staged/lint-staged/pull/1544)
[`5561321`](https://redirect.github.com/lint-staged/lint-staged/commit/556132176afce1701b4766c00ffd23159d437cb4)
Thanks [@&#8203;YimingIsCOLD](https://redirect.github.com/YimingIsCOLD)!
- Correctly handle colon (`:`) characters in staged filenames.

###
[`v15.5.1`](https://redirect.github.com/lint-staged/lint-staged/blob/HEAD/CHANGELOG.md#1551)

[Compare
Source](https://redirect.github.com/lint-staged/lint-staged/compare/v15.5.0...v15.5.1)

##### Patch Changes

-
[#&#8203;1533](https://redirect.github.com/lint-staged/lint-staged/pull/1533)
[`5d53534`](https://redirect.github.com/lint-staged/lint-staged/commit/5d535349958a939cd17d87180196bb2b9dfc452b)
Thanks [@&#8203;iiroj](https://redirect.github.com/iiroj)! - Improve
listing of staged files so that *lint-staged* doesn't crash when
encountering an uninitialized submodule. This should result in less
errors like:

        ✖ Failed to get staged files!

###
[`v15.5.0`](https://redirect.github.com/lint-staged/lint-staged/blob/HEAD/CHANGELOG.md#1550)

[Compare
Source](https://redirect.github.com/lint-staged/lint-staged/compare/v15.4.3...v15.5.0)

##### Minor Changes

-
[#&#8203;1526](https://redirect.github.com/lint-staged/lint-staged/pull/1526)
[`630af5f`](https://redirect.github.com/lint-staged/lint-staged/commit/630af5fb48ed43eb6ccaefa7a9d9612309023b6f)
Thanks [@&#8203;iiroj](https://redirect.github.com/iiroj)! - Lint-staged
no longer resets to the original state when preventing an empty git
commit. This happens when your configured tasks reset all the staged
changes, typically when trying to commit formatting changes which
conflict with your linter setup like ESLint or Prettier.

##### Example with Prettier

By default Prettier [prefers double
quotes](https://prettier.io/docs/rationale#strings).

##### Previously

1.  Stage `file.js` with only double quotes `"` changed to `'`
2.  Run `git commit -am "I don't like double quotes"`
3. *Lint-staged* runs `prettier --write file.js`, converting all the `'`
back to `"`
4. Because there are now no changes, *lint-staged* fails, cancels the
commit, and resets back to the original state
5. Commit was not done, original state is restored and single quotes `'`
are staged

##### Now

1.  Stage `file.js` with only double-quotes `"` changed to `'`
2.  Run `git commit -am "I don't like double quotes"`
3. *Lint-staged* runs `prettier --write file.js`, converting all the `'`
back to `"`
4. Because there are now no changes, *lint-staged* fails and cancels the
commit
5.  Commit was not done, and there are no staged changes

###
[`v15.4.3`](https://redirect.github.com/lint-staged/lint-staged/blob/HEAD/CHANGELOG.md#1543)

[Compare
Source](https://redirect.github.com/lint-staged/lint-staged/compare/v15.4.2...v15.4.3)

##### Patch Changes

-
[#&#8203;1512](https://redirect.github.com/lint-staged/lint-staged/pull/1512)
[`cbfed1d`](https://redirect.github.com/lint-staged/lint-staged/commit/cbfed1dfd2465c4198c692955281f0836600bea1)
Thanks [@&#8203;tarik02](https://redirect.github.com/tarik02)! - Adjust
TypeScript types for the default export so that it can be used as a
value without error TS2693.

###
[`v15.4.2`](https://redirect.github.com/lint-staged/lint-staged/blob/HEAD/CHANGELOG.md#1542)

[Compare
Source](https://redirect.github.com/lint-staged/lint-staged/compare/v15.4.1...v15.4.2)

##### Patch Changes

-
[#&#8203;1509](https://redirect.github.com/lint-staged/lint-staged/pull/1509)
[`8827ebf`](https://redirect.github.com/lint-staged/lint-staged/commit/8827ebf29dc8f25149a36450b4a0023425202e18)
Thanks [@&#8203;iiroj](https://redirect.github.com/iiroj)! - Change
*lint-staged*'s dependencies to use [caret (`^`)
ranges](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004)
instead of [tilde
(`~`)](https://docs.npmjs.com/cli/v6/using-npm/semver#tilde-ranges-123-12-1).
This makes it easier for package managers to perform dependency
management when minor-level updates are also permitted instead of just
patch-level.

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "" in timezone America/Los_Angeles,
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/x2od/.github).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xMDcuMCIsInVwZGF0ZWRJblZlciI6IjM5LjI2NC4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>